service: lambda-layer

plugins:
 - 'serverless-plugin-typescript'
 - serverless-plugin-optimize

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  profile : default
  iam:
    role: arn:aws:iam::302213478610:role/lambda-role
  vpc:
    subnetIds:
      - subnet-0c29051002d165a2c
      - subnet-0c29051002d165a2c
    securityGroupIds:
      - sg-029b80f0fd44eb16a

layers:
  ServiceDependencies:
    path: ./
    description: "Node Modules Dependencies"
