service: carbon-registry-services
package:
  exclude:
    - node_modules/**

plugins:
 - 'serverless-plugin-typescript'
 - serverless-plugin-optimize
 - serverless-offline

params:
 depLayerArn:
   Default: arn:aws:lambda:us-west-2:111111111111:layer:layer:1
   Type: String

provider:
 name: aws
 runtime: nodejs16.x
 stage: ${opt:stage, 'dev'}
 region: us-east-1
 environment:
   NODE_ENV: ${opt:stage, 'dev'} 

functions:
 national-api:
   handler: src/national-api/handler.handler
   events:
     - http:
         method: any
         path: /api/national/{any+}
   environment:
     NODE_PATH: "./:/opt/node_modules"
   layers:
     - ${param:depLayerArn}
 default:
   handler: src/shared/handler.handler
   events:
     - http:
         method: any
         path: /{any+}
   environment:
     NODE_PATH: "./:/opt/node_modules"
   layers:
     - ${param:depLayerArn}
custom:
  optimize:
    external: ['swagger-ui-dist']
