name: Deploy Services
on:
  push:
    branches:
      - develop
      - master
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  conditional_job_check_files:
    runs-on: ubuntu-latest
    # Declare outputs for next jobs
    outputs:
      deps_changed: ${{ steps.check_file_changed.outputs.deps_changed }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - shell: pwsh
      id: check_file_changed
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD
        $SourceDiff = $diff | Where-Object { $_ -match '^package.json' }
        $HasDiff = $SourceDiff.Length -gt 0

        # Set the output named "deps_changed"
        Write-Host "::set-output name=deps_changed::$HasDiff"
  layer:
    name: layer
    runs-on: ubuntu-latest
    needs: [ conditional_job_check_files ]
    if: needs.conditional_job_check_files.outputs.deps_changed == 'True'
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Copy package.json
        working-directory: ./lambda/layer
        run: cp ../services/package.json ./ && cp ../services/yarn.lock ./ && yarn install --frozen-lockfile
      - name: serverless deploy develop
        if: github.ref == 'refs/heads/develop'
        uses: serverless/github-action@v3.1
        with:
          args: -c "cd ./lambda/services && serverless deploy --stage dev"
          entrypoint: /bin/sh
      - name: serverless deploy master
        if: github.ref == 'refs/heads/master'
        uses: serverless/github-action@v3.1
        with:
          args: -c "cd ./lambda/services && serverless deploy --stage prod"
          entrypoint: /bin/sh
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [ layer ]
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependency
        working-directory: ./lambda/services
        run: yarn install --frozen-lockfile
      - name: Retrieve version
        run: |
          echo "ARN=$(aws lambda list-layer-versions --layer-name lambda-layer --region us-east-1 --query 'LayerVersions[0].LayerVersionArn')"
        id: layerArn
      - name: serverless deploy develop
        if: github.ref == 'refs/heads/develop'
        uses: serverless/github-action@v3.1
        with:
          args: -c "cd ./lambda/services && serverless deploy --stage dev --param='depLayerArn=${{ steps.version.outputs.ARN }}' "
          entrypoint: /bin/sh
      - name: serverless deploy master
        if: github.ref == 'refs/heads/master'
        uses: serverless/github-action@v3.1
        with:
          args: -c "cd ./lambda/services && serverless deploy --stage prod"
          entrypoint: /bin/sh