name: Deploy Dependency Layer
on:
  push:
    paths:
      - 'lambda/services/package.json'
    branches:
      - develop
      - master
defaults:
 run:
  working-directory: ./lambda/layer
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: cp ../services/package.json ./ && cp ../services/yarn.lock ./ && yarn install --frozen-lockfile
      - name: serverless deploy develop
        if: github.ref == 'refs/heads/develop'
        uses: serverless/github-action@v3.1
        with:
          args: -c "cd ./lambda/services && serverless deploy --stage dev"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: serverless deploy master
        if: github.ref == 'refs/heads/master'
        uses: serverless/github-action@v3.1
        with:
          args: -c "cd ./lambda/services && serverless deploy --stage prod"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}